#
# Pure Software Backend Driver Configuration
# This file contains the software dataplane driver config.
# Hardware vendor specific driver overrides have been stripped.
#

[virtio]
max_rxq=2
rx_desc=256
tx_desc=256
virtual=yes
limit-txq=yes
rx_mq_mode=eth_mq_rx_none

# use_all_txq needs to be set for the vhost PMD so that the
# dataplane has an equal number of TX and RX queues
[vhost]
rx_desc=256
tx_desc=256
virtual=yes
use_all_rxq=yes
use_all_txq=yes

[bonding]
max_rxq=2
rx_desc=2048
tx_desc=512
extra=2048
virtual=yes
limit-txq=yes
tx_offloads=!dev_tx_offload_multi_segs

# unit testing & software ring port; no tx_offloads necessary.
[net_ring]
max_rxq=2
rx_desc=512
tx_desc=128
tx_offloads=!dev_tx_offload_multi_segs,!dev_tx_offload_vlan_insert

[net_sw_port]
max_rxq=2
rx_desc=512
tx_desc=128
virtual=yes

[default]
max_rxq=2
rx_desc=512
tx_desc=128
virtual=yes
